pipeline {
    agent any
    stages {
        stage('npm install') {
            steps {
                sh 'npm install'
            }
        }
        stage('npm run build') {
            steps {
                sh 'npm run build'
            }
        }
    }
}