version: '3'
services:
  nodejs:
    build: ./node
    image: nodejs
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/.nuxt/
  phpapache:
    build: ./php
    ports:
      - "81:80"
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html
      - ./php/conf.d/custom.php.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql:
    build: ./mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306